CREATE DATABASE phpiggy;
GRANT ALL PRIVILEGES ON phpiggy.* TO 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON phpiggy.* TO 'root'@'localhost' IDENTIFIED BY '';
USE phpiggy;
CREATE TABLE IF NOT EXISTS users(
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  age TINYINT(3) UNSIGNED NOT NULL,
  country VARCHAR(255) NOT NULL,
  social_media_url VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY(id),
  UNIQUE KEY(email)
)